BROADCAST_NAD = 0x7F
BROADCAST_SUPPLIER_ID = 0x7fff
BROADCAST_FUNCTION_ID = 0xffff
MASTER_DIAGNOSTIC_FRAME_ID = 0x3C
SLAVE_DIAGNOSTIC_FRAME_ID = 0x3D


# SID's
READ_BY_IDENTIFIER_SID = 0xB2
ASSIGN_FRAME_IDENTIFIER_RANGE_SID = 0xB7
ASSIGN_NAD_SID = 0xB0
SAVE_CONFIGURATION_SID = 0xB6
CONDITIONAL_CHANGE_NAD_SID = 0xB3
ASSIGN_FRAME_IDENTIFIER_SID = 0xB1
DATA_DUMP_SID = 0xB4
ASSIGN_NAD_VIA_SNPD_SID = 0xb5

# Data Identifiers
DATA_IDENTIFIER_LIN_PRODUCT_IDENTIFIER = 0
DATA_IDENTIFIER_SERIAL_NUMBER = 1
