BROADCAST_NAD = 0x7F
BROADCAST_SUPPLIER_ID = 0x7fff
BROADCAST_FUNCTION_ID = 0xffff
MASTER_DIAGNOSTIC_FRAME_ID = 0x3C
SLAVE_DIAGNOSTIC_FRAME_ID = 0x3D


# SID's
READ_BY_IDENTIFIER_SID = 0xB2
ASSIGN_FRAME_ID_SID = 0xB1
ASSIGN_NAD_SID = 0xB0
SAVE_CONFIGURATION_SID = 0xB6

# Data Identifiers
DATA_IDENTIFIER_LIN_PRODUCT_IDENTIFIER = 0
DATA_IDENTIFIER_SERIAL_NUMBER = 1
